version: "3.4"

services:
  whatsapp-ai-reply:
    build: ./
    container_name: whatsapp-ai-reply
    restart: unless-stopped
    volumes:
      - ${DOCKER_APP_DATA}/whats-app-bot/data:/mnt/auth-data
    environment:
      SELF_CONTACT_ID: ${WHATSAPP_SELF_CONTACT_ID}
      OPEN_AI_API_KEY: ${OPEN_AI_KEY}
      OPEN_AI_MODEL_KEY: 'gpt-4-1106-preview'
      OPEN_AI_SYSTEM_PROMPT: 'You are an assistant who expands an emoji reponse to a message into a full text response'
